---
title: "Main"
author: "Peyman Kor"
date: "3/22/2022"
output:
  html_document:
    theme: cerulean
---

## Install the Required Libraries

```{r, error=FALSE, warning=FALSE, message=FALSE}

# library to manipulate data
library(tidyverse)

# library working with time data
library(lubridate)

# library to make word cloud
library(tm)
library(wordcloud)
library(SnowballC)
library(wordcloud2)

# library to work with x axis 
library(scales)
```


## Import the Varsle om feil (VOF) data

Link to the VOF dataset can be found here:

<https://open.stavanger.kommune.no/dataset/varsel-om-feil-vof>


```{r, error=TRUE, warning=FALSE, message=FALSE}
data_vof <- read_csv("https://opencom.no/dataset/6370c400-1fd2-45b0-a018-1362b7303088/resource/0a8d83a9-e0d2-4eae-a014-9562a49187b0/download/vof_csv.csv")

# We need convert DATO to appropritae DATE column
data_vof <-  data_vof %>% 
  mutate(DATE = ymd_hms(DATO))
```

## Make Word Cloud of the Data


```{r, warning=FALSE, message=FALSE}
# We only focus on the "PROBLEM" column of Data
problems_words <- Corpus(VectorSource(data_vof$PROBLEM))

# Cleaning Numbers and white spaces
problems_word_cleanI <- problems_words %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)


# lower case all the words
problems_word_cleanII <- tm_map(problems_word_cleanI, content_transformer(tolower))

problems_word_cleanIII <- tm_map(problems_word_cleanII, removeWords, stopwords("no"))


words_list <- TermDocumentMatrix(problems_word_cleanIII) 

# Make matrix of words
matrix <- as.matrix(words_list) 

# Make Freq and Word numbers
words_number <- sort(rowSums(matrix),decreasing=TRUE) 

df <- data.frame(word = names(words_number),freq=words_number)


wordcloud2::wordcloud2(data=df, size = 1.5, fontWeight = "bold")
```


## Questions To Start Dicussions:

### In The Categories of TEMA, whar are the Main reported Problem Per Month? 


```{r, fig.width=20, fig.height=14, fig.retina=2}

data_vof_tema <- data_vof %>% 
  drop_na() %>% 
  group_by(month = floor_date(DATE, unit = "month")) %>% 
  count(TEMA) %>% 
  mutate(date_new=as.Date(as.POSIXct(month, 'GMT'))) 

ggplot(data_vof_tema,aes(date_new, n)) +
  geom_bar(stat="identity", fill="darkblue") +
  facet_wrap(~TEMA, ncol = 1) +
  scale_x_date(date_breaks = "3 month", date_labels =  "%b %Y") +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  xlab("Month, Year") + ylab("Number of Feil Report") +
  theme(strip.background =element_rect(fill="grey")) +
  theme(text = element_text(size=24))

ggsave("TEMA_per_Year.png")

#ggsave("TEMA_per_Year.png", width = 20, height = 14, units = "cm", #dpi = 600)

```

### Inside the category of "Renovasjon", What are the Most reported Problems: 

```{r, fig.width=20, fig.height=14, fig.retina=2}

data_vof_tema_sub <- data_vof %>% 
  drop_na() %>% 
  filter(TEMA == c("'Renovasjon'")) %>% 
  filter(PROBLEM=="'Mangler bioposer/tømmekalender'" | PROBLEM=="'Ikke tømt restbeholder'") %>% 
  group_by(month = floor_date(DATE, unit = "month")) %>% 
  mutate(date_new=as.Date(as.POSIXct(month, 'GMT'))) %>% 
  count(PROBLEM)


ggplot(data_vof_tema_sub,aes(as.Date(as.POSIXct(month, 'GMT')), n)) +
  geom_bar(stat="identity", fill="darkblue") +
  facet_wrap(~PROBLEM, ncol = 1) +
  scale_x_date(date_breaks = "3 month", date_labels =  "%b %Y") +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=0.5)) +
  xlab("Month, Year") + ylab("Number of Feil Report") +
  theme(strip.background =element_rect(fill="grey")) +
  theme(text = element_text(size=24))
  #theme(strip.text.x = element_text(size = 16))

#ggsave("PROBLEM_per_Year_Renovasjon.png", width = 20, height = 14, units = "cm", dpi = 600)
ggsave("PROBLEM_per_Year_Renovasjon.png")
```
